services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  muse-db:
    image: ghcr.io/ust-quantil/mini-muse:main
  qhana-plugin-runner:
    image: ghcr.io/ust-quantil/qhana-plugin-runner:main
    depends_on:
      - redis-internal
      - postgres
    ports:
      - 5005:8080
    volumes:
      - instance:/app/instance
    environment:
      CONCURRENCY: 2
      BROKER_URL: redis://redis-internal:6379
      RESULT_BACKEND: redis://redis-internal:6379
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres:5432/default_db"
  worker:
    image: ghcr.io/ust-quantil/qhana-plugin-runner:main
    depends_on:
      - qhana-plugin-runner
    volumes:
      - instance:/app/instance
    environment:
      CONTAINER_MODE: worker
      CONCURRENCY: 2
      BROKER_URL: redis://redis-internal:6379
      RESULT_BACKEND: redis://redis-internal:6379
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres:5432/default_db"
  redis-internal:
    image: "redis:latest"
    ports:
      - "6378:6379"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: default_db
  backend:
    image: ghcr.io/ust-quantil/qhana-backend:main
    ports:
      - 9090:9090
  ui:
    image: ghcr.io/ust-quantil/qhana-ui:main
    ports:
      - 8080:8080
volumes:
  instance:
